# For Atom Feed
domain: jasontruluck.org
author: Jason Truluck
email: jason.truluck@gmail.com
title: Jason Truluck's Blog

# Analytics
google_analytics: UA-28345761-1

# Disqus
disqus_shortname: jasontruluck

# Jekyll Config
markdown: redcarpet

# Feed
feed_name: Jason Truluck's Blog
feed_burner: JasonTrulucksDevBlog

# Other
gravatar_id: 06dcf60f0a55f880a641f7bee802283d
timezone: America/New_York
